
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 21 23:28:35 CST 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos3 {
  /* terminals */
  public static final int TEXTO = 5;
  public static final int COMA = 2;
  public static final int ERROR = 4;
  public static final int error = 1;
  public static final int LINEA = 3;
  public static final int EOF = 0;
}

