
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 13 16:07:29 CST 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos3 {
  /* terminals */
  public static final int COMA = 3;
  public static final int TEXTO = 2;
  public static final int error = 1;
  public static final int LINEA = 4;
  public static final int EOF = 0;
}

