
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 12 01:51:20 CST 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int CARPETA = 5;
  public static final int ARCHIVO = 4;
  public static final int MENOR = 7;
  public static final int PROYECTO = 2;
  public static final int EOF = 0;
  public static final int NUMERO = 12;
  public static final int PALABRA = 14;
  public static final int CARACTERES = 13;
  public static final int DIAGONAL = 10;
  public static final int COMILLAS = 9;
  public static final int MAYOR = 8;
  public static final int IGUAL = 11;
  public static final int error = 1;
  public static final int NOMBRE = 3;
  public static final int UBICACION = 6;
}

