
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 12 17:03:04 CST 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos2 {
  /* terminals */
  public static final int COMA = 3;
  public static final int TEXTO = 2;
  public static final int error = 1;
  public static final int EOF = 0;
}

