
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 23 12:02:02 CST 2020
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class Simbolos2 {
  /* terminals */
  public static final int AND = 12;
  public static final int MENOR = 23;
  public static final int PUNTO = 17;
  public static final int INSERTAR = 6;
  public static final int IGUAL = 18;
  public static final int OR = 13;
  public static final int MENOR_IGUAL = 25;
  public static final int ELIMINAR = 9;
  public static final int ERROR = 15;
  public static final int MAYOR_IGUAL = 26;
  public static final int COMILLAS = 19;
  public static final int PATH_ARCHIVO = 14;
  public static final int FILTRAR = 5;
  public static final int VALORES = 10;
  public static final int ASIGNAR = 8;
  public static final int ACTUALIZAR = 7;
  public static final int COMA = 3;
  public static final int MAYOR = 24;
  public static final int ASTERISCO = 20;
  public static final int EOF = 0;
  public static final int DIFERENTE = 27;
  public static final int TEXTO = 2;
  public static final int error = 1;
  public static final int PUNTO_COMA = 16;
  public static final int EN = 11;
  public static final int PARENTECIS_C = 22;
  public static final int PARENTECIS_A = 21;
  public static final int SELECCIONAR = 4;
}

